name: Build

on:
  workflow_dispatch:

jobs:
  build-bicep:
    name: Build CLI (win-x64)
    runs-on: windows-latest

    env:
      # don't print dotnet logo
      DOTNET_NOLOGO: true

      # disable telemetry (reduces dotnet tool output in logs)
      DOTNET_CLI_TELEMETRY_OPTOUT: true

      CI: true

    strategy:
      # let us get failures from other jobs even if one fails
      fail-fast: false

      # should be the full list of supported RIDs with customizations expressed via the parameters under each item
      matrix:
        include:
          - attempt: 0
          - attempt: 1
          - attempt: 2
          - attempt: 3
          - attempt: 4
          - attempt: 5
          - attempt: 6
          - attempt: 7
          - attempt: 8
          - attempt: 9

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
          submodules: true

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2

      - name: Test ${{ matrix.attempt }}
        run: dotnet test src/Bicep.Core.UnitTests --configuration release --logger trx --blame --collect:"XPlat Code Coverage" --settings ./.github/workflows/codecov.runsettings --results-directory ./TestResults/